name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update version
      run: |
        if [ ! -f version.txt ]; then
          echo "1.0.0" > version.txt
        else
          current_version=$(cat version.txt)
          new_version=$(echo $current_version | awk -F. '{$NF+=1; OFS="."; print $0}')
          echo $new_version > version.txt
        fi

    - name: Create publish directory
      run: |
        mkdir publish

    - name: Copy files to publish directory
      run: |
        cp dist/AutoLottery539.exe publish/
        cp config.ini publish/
        cp version.txt publish/

    - name: Zip publish directory
      run: |
        zip -r output.zip publish/

    - name: Publish release
      uses: softprops/action-gh-release@v1
      with:
        files: output.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_NAME: "Release ${{ cat version.txt }}"
