name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 檢查倉庫
      uses: actions/checkout@v2

    - name: 設置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: 安裝相依套件
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 更新版本號
      run: |
        if [ ! -f version.txt ]; then
          echo "1.0.0" > version.txt
        else
          current_version=$(<version.txt)
          new_version=$(echo $current_version | awk -F. '{$NF+=1; OFS="."; print $0}')
          echo $new_version > version.txt
        fi

    - name: 創建發布目錄
      run: |
        mkdir publish

    - name: 複製檔案到發布目錄
      run: |
        cp dist/AutoLottery539.exe publish/
        cp config.ini publish/
        cp version.txt publish/

    - name: 將發布目錄壓縮
      run: |
        zip -r output.zip publish/

    - name: 創建標籤
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git tag -a v$(< version.txt) -m "Release version $(< version.txt)"
        git push origin --tags

    - name: 發布 Release
      uses: softprops/action-gh-release@v1
      with:
        files: output.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_NAME: "Release $(< version.txt)"
