name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 檢查倉庫
      uses: actions/checkout@v2

    - name: 設置 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: 安裝相依套件
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 更新版本號
      run: |
        date_string=$(date +'%Y%m%d%H%M%S')
        echo $date_string > version.txt

    - name: 創建發布目錄
      run: |
        mkdir publish

    - name: 複製檔案到發布目錄
      run: |
        cp dist/AutoLottery539.exe publish/
        cp config.ini publish/
        cp version.txt publish/

    - name: 將發布目錄壓縮
      run: |
        zip -r output.zip publish/

    - name: 显示版本号
      run: echo v$(< version.txt)
    
    - name: 获取版本号
      id: get_version
      run: echo ::set-output name=tag_name::$(< version.txt)
    
    - name: 發布 Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.tag_name }}
        RELEASE_NAME: "Release ${{ steps.get_version.outputs.tag_name }}"
        draft: false
        prerelease: false
